### ISSUE TITLE
退出后部分情况显示有问题

### ISSUE THREAD

**Issue by Marchf** [bpm-activiti/bpm-testing#15]
![image](https://user-images.githubusercontent.com/36831441/36785217-0b7fbb64-1cbd-11e8-81e3-f135a1d78105.png)

**Comment by Marchf** [comment]
@richardzhai01 @QinghongXiao

**Comment by QinghongXiao** [comment]
fixed 
修改路由访问方式。 如图
![image](https://user-images.githubusercontent.com/22759883/36832645-46094f7a-1d67-11e8-877a-79b04aef982e.png)
打包后测试是可以正常退出的。

**Comment by Marchf** [comment]
![image](https://user-images.githubusercontent.com/36831441/36887375-dfefce38-1e2b-11e8-90e4-dc902ed02414.png)

退出时还是有这些问题。缓存清理了，后台没有报错。

**Comment by Marchf** [comment]
http://192.168.243.1:8080/auth/realms/spring-security/protocol/openid-connect/logout?redirect_uri=http%3A%2F%2F192.168.243.128%3A8333%2Fscnea%2F%23%2Fprocess%2Fmy
