### ISSUE TITLE
显示page的时候，选择10的行数时，没有显示10行的数据

### ISSUE THREAD

**Issue by richardzhai01** [bpm-activiti/bpm-testing#3]
![image](https://user-images.githubusercontent.com/17737516/36655175-021e4dc8-1afc-11e8-890b-82835f62c717.png)

**Comment by QinghongXiao** [comment]
fixed

![image](https://user-images.githubusercontent.com/22759883/36659834-c388dbea-1b10-11e8-9193-87033711859a.png)
