### ISSUE TITLE
登录超时判断

### ISSUE THREAD

**Issue by Marchf** [bpm-activiti/bpm-testing#39]
![image](https://user-images.githubusercontent.com/36831441/36935468-0f741b0c-1f33-11e8-84e5-48c97261cd89.png)

![image](https://user-images.githubusercontent.com/36831441/36935479-3f231b46-1f33-11e8-9d9f-4fe3c76e36c5.png)

这个用户是我刚刚登录上来的，点击任务就会提示登录超时。遇到过很多次了。
@richardzhai01 @QinghongXiao

**Comment by QinghongXiao** [comment]
fixed 
已加大formio超时设置。 请留意是否还有timeout
