### ISSUE TITLE
Claim的按钮没有显示出来

### ISSUE THREAD

**Issue by richardzhai01** [bpm-activiti/bpm-testing#4]
![image](https://user-images.githubusercontent.com/17737516/36655236-4dfa189e-1afc-11e8-80e4-2bc12e04bd00.png)

**Comment by QinghongXiao** [comment]
fixed
![image](https://user-images.githubusercontent.com/22759883/36657095-2b598b62-1b06-11e8-9261-9063859a1012.png)
