### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by Marchf** [bpm-activiti/bpm-testing#49]
![image](https://user-images.githubusercontent.com/36831441/37701182-0953b382-2d29-11e8-98a0-f00c85627049.png)

![image](https://user-images.githubusercontent.com/36831441/37701239-2caed168-2d29-11e8-85fa-e2a8a8022cef.png)

用户、formio、app、流程都是最新创建的，而且在登录之前是已经分配好了权限。等到启动后申领流程，打开后提示Unauthorized。

**Comment by QinghongXiao** [comment]
看你截的图是没有将formio 的 auth权限赋给用户。

**Comment by Marchf** [comment]
我还以为只需要赋task权限给他就可以执行。也就是他不需要编辑formio但是需要再执行过程中用到formio也要赋该权限的意思吧。

**Comment by Marchf** [comment]
![image](https://user-images.githubusercontent.com/36831441/37753446-f6d4c732-2dd7-11e8-89e0-a53b7aaf01f0.png)
重新新建的一个用户company3，没有登录过，分配了以上权限。
![image](https://user-images.githubusercontent.com/36831441/37753478-163d4734-2dd8-11e8-8291-bd8e373ccd27.png)
任务申领之后点击进入该任务提示

@QinghongXiao @richardzhai01

**Comment by Marchf** [comment]
配置影响整个使用。现在测试正常了
