### ISSUE TITLE
Claim Task双击后就可以进入task detail，而且有complete的按钮，这是不允许的

### ISSUE THREAD

**Issue by richardzhai01** [bpm-activiti/bpm-testing#5]
Claim Task只能claim task， 只有在自己的列表里面，才可以打开complete
![image](https://user-images.githubusercontent.com/17737516/36655287-b8ab2d0e-1afc-11e8-8cf3-7dbdb54179a7.png)

![image](https://user-images.githubusercontent.com/17737516/36655307-cf5fb902-1afc-11e8-819a-bd3b263abcf1.png)

**Comment by QinghongXiao** [comment]
fixed 
在cliam 列表里， 不可进入taskdetail
![image](https://user-images.githubusercontent.com/22759883/36659093-40b14858-1b0e-11e8-906a-db62046406ce.png)
