### ISSUE TITLE
右上角的search的按钮暂时隐藏

### ISSUE THREAD

**Issue by richardzhai01** [bpm-activiti/bpm-testing#6]
![image](https://user-images.githubusercontent.com/17737516/36655375-31bb8216-1afd-11e8-8bb8-46fef8ae1c0a.png)

**Comment by QinghongXiao** [comment]
fixed 

![image](https://user-images.githubusercontent.com/22759883/36660056-a5f6f764-1b11-11e8-947d-c11b2a364474.png)
